# Generated by Django 3.0.10 on 2020-10-27 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='deleted')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Mobile Number', regex='[1-9]\\d{9}')], verbose_name='Mobile Number')),
                ('country_code', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Country Code', regex='^\\+[0-9]{1, 4}')], verbose_name='Country Code')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('alternate_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alternate Mobile Number')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Occupation')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.State')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
