version: "3.9"

x-common-variables: &common-variables
  POSTGRES_USER: debug
  POSTGRES_PASSWORD: debug
  POSTGRES_DB: medical

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      <<: *common-variables
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data postgres
    networks:
      - cxd

  cxdfrontend:
    build:
      context: ./cxd_frontend
      dockerfile: Dockerfile
    container_name: cxdfrontend
    restart: always
    environment: 
      BACKEND_URL: http://cxdbackend:8000
      MODEL_SERVING: http://cxdmodel:8001
    ports:
      - 3000:3000
    expose:
      - 3000
    # volumes:
    #   - ./cxd_backend:/app
    networks:
      - cxd

  cxdbackend:
    build:
      context: ./cxd_backend
      dockerfile: Dockerfile
    container_name: cxdbackend
    restart: always
    depends_on:
      - postgres
    environment:
      <<: *common-variables
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DJANGO_ALLOWED_HOSTS: 'cxdfrontend,cxdbackend'
      DJANGO_CORS_HOSTS: 'http://cxdfrontend,http://cxdbackend'
    stdin_open: true
    ports:
      - 8000:8000
    expose:
      - 8000
    # volumes:
    #   - ./cxd_frontend/src:/app/src
    #   - ./cxd_frontend/public:/app/public
    networks:
      - cxd

  # cxdmodel:
  #   build:
  #     context: ./cxd_model
  #     dockerfile: Dockerfile
  #   container_name: cxdmodel
  #   restart: always
  #   ports:
  #     - 8001:8001
  #   expose:
  #     - 8001
  #   networks:
  #     - cxd

volumes:
  pgdata:

networks:
  cxd:
    driver: bridge


