export const LOADING_USER_DETAILS = 'LOADING_USER_DETAILS';

export const LOAD_USER_DETAILS_SUCCESS = 'LOAD_USER_DETAILS_SUCCESS';

export const LOAD_USER_DETAILS_FAILURE = 'LOAD_USER_DETAILS_FAILURE';