export const LOADING_DIAGNOSIS_RESULTS = 'LOADING_DIAGNOSIS_RESULTS';

export const LOAD_DIAGNOSIS_RESULTS_SUCCESS = 'LOAD_DIAGNOSIS_RESULTS_SUCCESS';

export const LOAD_DIAGNOSIS_RESULTS_FAILURE = 'LOAD_DIAGNOSIS_RESULTS_FAILURE';